<?php

    if ( ! class_exists( 'Redux' ) ) {
        return;
    }

    // This is your option name where all the Redux data is stored.
    $opt_name = "sohohotel_data";

    $theme = wp_get_theme(); // For use with some settings. Not necessary.
	
    $args = array(   
        'opt_name'             => $opt_name,
        'display_name'         => $theme->get( 'Name' ),
        'display_version'      => $theme->get( 'Version' ),
        'menu_type'            => 'menu',
        'allow_sub_menu'       => false,
        'menu_title'           => esc_html__( 'Theme Options', 'sohohotel' ),
        'page_title'           => esc_html__( 'Theme Options', 'sohohotel' ),
        'google_api_key'       => '',
        'google_update_weekly' => false,
        'async_typography'     => true,
        'admin_bar'            => true,
        'admin_bar_icon'       => 'dashicons-portfolio',
        'admin_bar_priority'   => 50,
        'global_variable'      => '',
        'dev_mode'             => false,
        'update_notice'        => true,
        'customizer'           => true,
        'page_priority'        => null,
        'page_parent'          => 'themes.php',
        'page_permissions'     => 'manage_options',
        'menu_icon'            => '',
        'last_tab'             => '',
        'page_icon'            => 'icon-themes',
        'page_slug'            => '',
        'save_defaults'        => true,
        'default_show'         => false,
        'default_mark'         => '',
        'show_import_export'   => true,
        'transient_time'       => 60 * MINUTE_IN_SECONDS,
        'output'               => true,
        'output_tag'           => true,
        'database'             => '',
        'use_cdn'              => true,
        'hints'                => array(
            'icon'          => 'el el-question-sign',
            'icon_position' => 'right',
            'icon_color'    => 'lightgray',
            'icon_size'     => 'normal',
            'tip_style'     => array(
                'color'   => 'red',
                'shadow'  => true,
                'rounded' => false,
                'style'   => '',
            ),
            'tip_position'  => array(
                'my' => 'top left',
                'at' => 'bottom right',
            ),
            'tip_effect'    => array(
                'show' => array(
                    'effect'   => 'slide',
                    'duration' => '500',
                    'event'    => 'mouseover',
                ),
                'hide' => array(
                    'effect'   => 'slide',
                    'duration' => '500',
                    'event'    => 'click mouseleave',
                ),
            ),
        )
    );

    Redux::setArgs( $opt_name, $args );

    Redux::setSection( $opt_name, array(
        'title'            => esc_html__( 'General', 'sohohotel' ),
        'id'               => 'general',
        'desc'             => '',
        'customizer_width' => '400px',
        'icon'             => 'el el-home',
		'fields'           => array(
			array(
                'id'       => 'site-layout-style',
                'type'     => 'radio',
                'title'    => esc_html__( 'Site Default Layout Style', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'options'  => array(
                    'right-sidebar' => 'Right Sidebar',
					'left-sidebar' => 'Left Sidebar',
                    'full-width' => 'Full Width'
                ),
                'default'  => 'right-sidebar'
            ),
			array(
				'id'       => 'background-layout-style',
				'type'     => 'radio',
				'title'    => esc_html__( 'Background Layout Style', 'sohohotel' ),
				'subtitle' => '',
				'desc'     => '',
				'options'  => array(
					'boxed' => 'Boxed',
					'full-width' => 'Full Width'
				),
				'default'  => 'boxed'
			),
			array(
				'id'       => 'site-header-style',
				'type'     => 'radio',
				'title'    => esc_html__( 'Header Style', 'sohohotel' ),
				'subtitle' => '',
				'desc'     => '',
				'options'  => array(
					'sohohotel-header1' => 'Header 1',
					'sohohotel-header2' => 'Header 2',
					'sohohotel-header3' => 'Header 3',
					'sohohotel-header4' => 'Header 4',
				),
				'default'  => 'sohohotel-header1'
			),
			array(
                'id'       => 'top-right-menu',
                'type'     => 'checkbox',
                'title'    => esc_html__( 'Enable Top Right Menu For Language Selection', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => '0'// 1 = on | 0 = off
            ),
			array(
                'id'       => 'top-left-phone',
                'type'     => 'text',
                'title'    => esc_html__( 'Top Left Phone Number', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => '1800-1111-2222',
            ),
			array(
                'id'       => 'top-left-address',
                'type'     => 'text',
                'title'    => esc_html__( 'Top Left Address', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => '700 5th Avenue, New York City, United States',
            ),
			array(
                'id'       => 'top-right-menu-text',
                'type'     => 'text',
                'title'    => esc_html__( 'Top Right Menu Text', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => 'Languages:',
            ),
			array(
                'id'       => 'top-right-button-text',
                'type'     => 'text',
                'title'    => esc_html__( 'Top Right Button Text', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => 'Book Now',
            ),
			array(
                'id'       => 'top-right-button-link-target',
                'type'     => 'checkbox',
                'title'    => esc_html__( 'Open top right button in new window/tab', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => '0'// 1 = on | 0 = off
            ),
			array(
                'id'       => 'google-map-api-key',
                'type'     => 'text',
                'title'    => esc_html__( 'Google Map API Key', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => '',
            ),
			array(
                'id'       => 'footer-message',
                'type'     => 'text',
                'title'    => esc_html__( 'Footer Message', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'Text displayed in the bottom center of the site footer', 'sohohotel' ),
                'default'  => '&copy; 2017 Soho Hotel. All Rights Reserved',
            ),
			array(
                'id'       => 'accommodation_slug',
                'type'     => 'text',
                'title'    => esc_html__( 'Accommodation Page Slug', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'Used in the breadcrumbs, only add the page slug e.g. "page-slug", not "http://website.com/page-slug"', 'sohohotel' ),
                'default'  => '',
            ),
			array(
                'id'       => 'testimonials_slug',
                'type'     => 'text',
                'title'    => esc_html__( 'Testimonials Page Slug', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'Used in the breadcrumbs, only add the page slug e.g. "page-slug", not "http://website.com/page-slug"', 'sohohotel' ),
                'default'  => '',
            )
		)
	) );
	Redux::setSection( $opt_name, array(
	    'title'            => esc_html__( 'Bookings', 'sohohotel' ),
	    'id'               => 'bookings',
	    'desc'             => '',
	    'customizer_width' => '400px',
	    'icon'             => 'el el-calendar',
		'fields'           => array(
			array(
                'id'       => 'booking-email',
                'type'     => 'text',
                'title'    => esc_html__( 'Email Address', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'The email address booking notifications are sent to', 'sohohotel' ),
                'default'  => '',
            ),
			array(
                'id'       => 'email-sender-name',
                'type'     => 'text',
                'title'    => esc_html__( 'Email Sender Name', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'The name of the email sender booking notifications are send from', 'sohohotel' ),
                'default'  => 'Soho Hotel',
            ),
			array(
                'id'       => 'booking-phone',
                'type'     => 'text',
                'title'    => esc_html__( 'Phone Number', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => '',
            ),
			array(
                'id'       => 'booking-address',
                'type'     => 'text',
                'title'    => esc_html__( 'Address', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => '',
            ),
			array(
			    'id'       => 'tax-rate',
			    'type'     => 'select',
			    'title'    => esc_html__( 'Tax Percentage', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'Automatically added to the total booking price', 'sohohotel' ),
			    'options'  => array(
					'none' => 'None',
					'1' => '1%',
					'2' => '2%',
					'3' => '3%',
					'4' => '4%',
					'5' => '5%',
					'6' => '6%',
					'7' => '7%',
					'8' => '8%',
					'9' => '9%',
					'10' => '10%',
					'11' => '11%',
					'12' => '12%',
					'13' => '13%',
					'14' => '14%',
					'15' => '15%',
					'16' => '16%',
					'17' => '17%',
					'18' => '18%',
					'19' => '19%',
					'20' => '20%',
					'21' => '21%',
					'22' => '22%',
					'23' => '23%',
					'24' => '24%',
					'25' => '25%',
					'26' => '26%',
					'27' => '27%',
					'28' => '28%',
					'29' => '29%',
					'30' => '30%',
					'31' => '31%',
					'32' => '32%',
					'33' => '33%',
					'34' => '34%',
					'35' => '35%',
					'36' => '36%',
					'37' => '37%',
					'38' => '38%',
					'39' => '39%',
					'40' => '40%',
					'41' => '41%',
					'42' => '42%',
					'43' => '43%',
					'44' => '44%',
					'45' => '45%',
					'46' => '46%',
					'47' => '47%',
					'48' => '48%',
					'49' => '49%',
					'50' => '50%',
					'51' => '51%',
					'52' => '52%',
					'53' => '53%',
					'54' => '54%',
					'55' => '55%',
					'56' => '56%',
					'57' => '57%',
					'58' => '58%',
					'59' => '59%',
					'60' => '60%',
					'61' => '61%',
					'62' => '62%',
					'63' => '63%',
					'64' => '64%',
					'65' => '65%',
					'66' => '66%',
					'67' => '67%',
					'68' => '68%',
					'69' => '69%',
					'70' => '70%',
					'71' => '71%',
					'72' => '72%',
					'73' => '73%',
					'74' => '74%',
					'75' => '75%',
					'76' => '76%',
					'77' => '77%',
					'78' => '78%',
					'79' => '79%',
					'80' => '80%',
					'81' => '81%',
					'82' => '82%',
					'83' => '83%',
					'84' => '84%',
					'85' => '85%',
					'86' => '86%',
					'87' => '87%',
					'88' => '88%',
					'89' => '89%',
					'90' => '90%',
					'91' => '91%',
					'92' => '92%',
					'93' => '93%',
					'94' => '94%',
					'95' => '95%',
					'96' => '96%',
					'97' => '97%',
					'98' => '98%',
					'99' => '99%',
					'100' => '100%'
			    ),
			    'default'  => 'none',
			),
			array(
                'id'       => 'do_not_record_bookings',
                'type'     => 'checkbox',
                'title'    => esc_html__( 'Do not record bookings into database', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'The availability checker will not work if you check this option', 'sohohotel' ),
                'default'  => '0'// 1 = on | 0 = off
            ),
			array(
                'id'       => 'manual_booking_confirmation',
                'type'     => 'checkbox',
                'title'    => esc_html__( 'Manually Confirm Bookings', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'If you check this option the room will not be made unavailable until the booking status is manually updated to "confirmed"' ),
                'default'  => '0'// 1 = on | 0 = off
            ),
			array(
			    'id'       => 'booking_show_remaining_rooms',
			    'type'     => 'select',
			    'title'    => __('Show the number of remaining rooms available when there are how many left?', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => '',
			    'options'  => array(
					'never' => 'Never',
					'1' => '1',
					'2' => '2',
					'3' => '3',
					'4' => '4',
					'5' => '5',
					'6' => '6',
					'7' => '7',
					'8' => '8',
					'9' => '9',
					'10' => '10',
					'11' => '11',
					'12' => '12',
					'13' => '13',
					'14' => '14',
					'15' => '15',
					'16' => '16',
					'17' => '17',
					'18' => '18',
					'19' => '19',
					'20' => '20',
					'21' => '21',
					'22' => '22',
					'23' => '23',
					'24' => '24',
					'25' => '25',
					'26' => '26',
					'27' => '27',
					'28' => '28',
					'29' => '29',
					'30' => '30'
			    ),
			    'default'  => '3',
			),
			array(
			    'id'       => 'booking_form_max_person',
			    'type'     => 'select',
			    'title'    => __('Maximum persons to show on booking form', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => '',
			    'options'  => array(
					'1' => '1',
					'2' => '2',
					'3' => '3',
					'4' => '4',
					'5' => '5',
					'6' => '6',
					'7' => '7',
					'8' => '8',
					'9' => '9',
					'10' => '10',
					'11' => '11',
					'12' => '12',
					'13' => '13',
					'14' => '14',
					'15' => '15',
					'16' => '16',
					'17' => '17',
					'18' => '18',
					'19' => '19',
					'20' => '20',
					'21' => '21',
					'22' => '22',
					'23' => '23',
					'24' => '24',
					'25' => '25',
					'26' => '26',
					'27' => '27',
					'28' => '28',
					'29' => '29',
					'30' => '30'
			    ),
			    'default'  => '5',
			),
			array(
			    'id'       => 'booking_form_max_rooms',
			    'type'     => 'select',
			    'title'    => __('Maximum rooms per booking', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => '',
			    'options'  => array(
					'1' => '1',
					'2' => '2',
					'3' => '3',
					'4' => '4',
					'5' => '5',
					'6' => '6',
					'7' => '7',
					'8' => '8',
					'9' => '9',
					'10' => '10',
					'11' => '11',
					'12' => '12',
					'13' => '13',
					'14' => '14',
					'15' => '15',
					'16' => '16',
					'17' => '17',
					'18' => '18',
					'19' => '19',
					'20' => '20',
					'21' => '21',
					'22' => '22',
					'23' => '23',
					'24' => '24',
					'25' => '25',
					'26' => '26',
					'27' => '27',
					'28' => '28',
					'29' => '29',
					'30' => '30'
			    ),
			    'default'  => '5',
			),
			array(
			    'id'       => 'minimum_stay',
			    'type'     => 'select',
			    'title'    => __('Minimum stay', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => '',
			    'options'  => array(
					'1' => '1 Night',
					'2' => '2 Nights',
					'3' => '3 Nights',
					'4' => '4 Nights',
					'5' => '5 Nights',
					'6' => '6 Nights',
					'7' => '7 Nights',
					'8' => '8 Nights',
					'9' => '9 Nights',
					'10' => '10 Nights',
					'11' => '11 Nights',
					'12' => '12 Nights',
					'13' => '13 Nights',
					'14' => '14 Nights',
					'15' => '15 Nights',
					'16' => '16 Nights',
					'17' => '17 Nights',
					'18' => '18 Nights',
					'19' => '19 Nights',
					'20' => '20 Nights',
					'21' => '21 Nights',
					'22' => '22 Nights',
					'23' => '23 Nights',
					'24' => '24 Nights',
					'25' => '25 Nights',
					'26' => '26 Nights',
					'27' => '27 Nights',
					'28' => '28 Nights',
					'29' => '29 Nights',
					'30' => '30 Nights',
					'30' => '31 Nights',
					'31' => '32 Nights',
					'32' => '33 Nights',
					'34' => '34 Nights',
					'35' => '35 Nights',
					'36' => '36 Nights',
					'37' => '37 Nights',
					'38' => '38 Nights',
					'39' => '39 Nights',
					'40' => '40 Nights',
					'41' => '41 Nights',
					'42' => '42 Nights',
					'43' => '43 Nights',
					'44' => '44 Nights',
					'45' => '45 Nights',
					'46' => '46 Nights',
					'47' => '47 Nights',
					'48' => '48 Nights',
					'49' => '49 Nights',
					'50' => '50 Nights',
					'51' => '51 Nights',
					'52' => '52 Nights',
					'53' => '53 Nights',
					'54' => '54 Nights',
					'55' => '55 Nights',
					'56' => '56 Nights',
					'57' => '57 Nights',
					'58' => '58 Nights',
					'59' => '59 Nights',
					'60' => '60 Nights',
					'61' => '61 Nights',
					'62' => '62 Nights',
					'63' => '63 Nights',
					'64' => '64 Nights',
					'65' => '65 Nights',
					'66' => '66 Nights',
					'67' => '67 Nights',
					'68' => '68 Nights',
					'69' => '69 Nights',
					'70' => '70 Nights',
					'70' => '71 Nights',
					'71' => '72 Nights',
					'72' => '73 Nights',
					'74' => '74 Nights',
					'75' => '75 Nights',
					'76' => '76 Nights',
					'77' => '77 Nights',
					'78' => '78 Nights',
					'79' => '79 Nights',
					'80' => '80 Nights',
					'81' => '81 Nights',
					'82' => '82 Nights',
					'83' => '83 Nights',
					'84' => '84 Nights',
					'85' => '85 Nights',
					'86' => '86 Nights',
					'87' => '87 Nights',
					'88' => '88 Nights',
					'89' => '89 Nights',
					'90' => '90 Nights',
					'91' => '91 Nights',
					'92' => '92 Nights',
					'93' => '93 Nights',
					'94' => '94 Nights',
					'95' => '95 Nights',
					'96' => '96 Nights',
					'97' => '97 Nights',
					'98' => '98 Nights',
					'99' => '99 Nights',
					'100' => '100 Nights'
			    ),
			    'default'  => '5',
			),
			array(
			    'id'       => 'date_format',
			    'type'     => 'select',
			    'title'    => __('Date format', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => '',
			    'options'  => array(
					'dd/mm/yy' => 'DD/MM/YYYY',
					'mm/dd/yy' => 'MM/DD/YYYY',
					'yy/mm/dd' => 'YYYY/MM/DD'
			    ),
			    'default'  => 'dd/mm/yy',
			),
			array(
			    'id'       => 'weekend_nights',
			    'type'     => 'select',
			    'title'    => __('Weekend Nights', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => __('Nights which use "weekend" prices', 'sohohotel'),
			    'options'  => array(
					'1' => 'Fri/Sat',
					'2' => 'Sat/Sun',
					'3' => 'Fri/Sat/Sun'
			    ),
			    'default'  => '1',
			),
			array(
			    'id'       => 'weekly_booking_nights',
			    'type'     => 'select',
			    'title'    => __('Weekly Booking Nights', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => __('Number of nights a guest must book to qualify for "weekly" booking prices', 'sohohotel'),
			    'options'  => array(
					'1' => '1 Night',
					'2' => '2 Nights',
					'3' => '3 Nights',
					'4' => '4 Nights',
					'5' => '5 Nights',
					'6' => '6 Nights',
					'7' => '7 Nights',
					'8' => '8 Nights',
					'9' => '9 Nights',
					'10' => '10 Nights',
					'11' => '11 Nights',
					'12' => '12 Nights',
					'13' => '13 Nights',
					'14' => '14 Nights',
					'15' => '15 Nights',
					'16' => '16 Nights',
					'17' => '17 Nights',
					'18' => '18 Nights',
					'19' => '19 Nights',
					'20' => '20 Nights',
					'21' => '21 Nights',
					'22' => '22 Nights',
					'23' => '23 Nights',
					'24' => '24 Nights',
					'25' => '25 Nights',
					'26' => '26 Nights',
					'27' => '27 Nights',
					'28' => '28 Nights',
					'29' => '29 Nights',
					'30' => '30 Nights',
					'30' => '31 Nights',
					'31' => '32 Nights',
					'32' => '33 Nights',
					'34' => '34 Nights',
					'35' => '35 Nights',
					'36' => '36 Nights',
					'37' => '37 Nights',
					'38' => '38 Nights',
					'39' => '39 Nights',
					'40' => '40 Nights',
					'41' => '41 Nights',
					'42' => '42 Nights',
					'43' => '43 Nights',
					'44' => '44 Nights',
					'45' => '45 Nights',
					'46' => '46 Nights',
					'47' => '47 Nights',
					'48' => '48 Nights',
					'49' => '49 Nights',
					'50' => '50 Nights',
					'51' => '51 Nights',
					'52' => '52 Nights',
					'53' => '53 Nights',
					'54' => '54 Nights',
					'55' => '55 Nights',
					'56' => '56 Nights',
					'57' => '57 Nights',
					'58' => '58 Nights',
					'59' => '59 Nights',
					'60' => '60 Nights',
					'61' => '61 Nights',
					'62' => '62 Nights',
					'63' => '63 Nights',
					'64' => '64 Nights',
					'65' => '65 Nights',
					'66' => '66 Nights',
					'67' => '67 Nights',
					'68' => '68 Nights',
					'69' => '69 Nights',
					'70' => '70 Nights',
					'70' => '71 Nights',
					'71' => '72 Nights',
					'72' => '73 Nights',
					'74' => '74 Nights',
					'75' => '75 Nights',
					'76' => '76 Nights',
					'77' => '77 Nights',
					'78' => '78 Nights',
					'79' => '79 Nights',
					'80' => '80 Nights',
					'81' => '81 Nights',
					'82' => '82 Nights',
					'83' => '83 Nights',
					'84' => '84 Nights',
					'85' => '85 Nights',
					'86' => '86 Nights',
					'87' => '87 Nights',
					'88' => '88 Nights',
					'89' => '89 Nights',
					'90' => '90 Nights',
					'91' => '91 Nights',
					'92' => '92 Nights',
					'93' => '93 Nights',
					'94' => '94 Nights',
					'95' => '95 Nights',
					'96' => '96 Nights',
					'97' => '97 Nights',
					'98' => '98 Nights',
					'99' => '99 Nights',
					'100' => '100 Nights'
			    ),
			    'default'  => '6',
			),
			array(
			    'id'       => 'monthly_booking_nights',
			    'type'     => 'select',
			    'title'    => __('Monthly Booking Nights', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => __('Number of nights a guest must book to qualify for "monthly" booking prices', 'sohohotel'),
			    'options'  => array(
					'1' => '1 Night',
					'2' => '2 Nights',
					'3' => '3 Nights',
					'4' => '4 Nights',
					'5' => '5 Nights',
					'6' => '6 Nights',
					'7' => '7 Nights',
					'8' => '8 Nights',
					'9' => '9 Nights',
					'10' => '10 Nights',
					'11' => '11 Nights',
					'12' => '12 Nights',
					'13' => '13 Nights',
					'14' => '14 Nights',
					'15' => '15 Nights',
					'16' => '16 Nights',
					'17' => '17 Nights',
					'18' => '18 Nights',
					'19' => '19 Nights',
					'20' => '20 Nights',
					'21' => '21 Nights',
					'22' => '22 Nights',
					'23' => '23 Nights',
					'24' => '24 Nights',
					'25' => '25 Nights',
					'26' => '26 Nights',
					'27' => '27 Nights',
					'28' => '28 Nights',
					'29' => '29 Nights',
					'30' => '30 Nights',
					'30' => '31 Nights',
					'31' => '32 Nights',
					'32' => '33 Nights',
					'34' => '34 Nights',
					'35' => '35 Nights',
					'36' => '36 Nights',
					'37' => '37 Nights',
					'38' => '38 Nights',
					'39' => '39 Nights',
					'40' => '40 Nights',
					'41' => '41 Nights',
					'42' => '42 Nights',
					'43' => '43 Nights',
					'44' => '44 Nights',
					'45' => '45 Nights',
					'46' => '46 Nights',
					'47' => '47 Nights',
					'48' => '48 Nights',
					'49' => '49 Nights',
					'50' => '50 Nights',
					'51' => '51 Nights',
					'52' => '52 Nights',
					'53' => '53 Nights',
					'54' => '54 Nights',
					'55' => '55 Nights',
					'56' => '56 Nights',
					'57' => '57 Nights',
					'58' => '58 Nights',
					'59' => '59 Nights',
					'60' => '60 Nights',
					'61' => '61 Nights',
					'62' => '62 Nights',
					'63' => '63 Nights',
					'64' => '64 Nights',
					'65' => '65 Nights',
					'66' => '66 Nights',
					'67' => '67 Nights',
					'68' => '68 Nights',
					'69' => '69 Nights',
					'70' => '70 Nights',
					'70' => '71 Nights',
					'71' => '72 Nights',
					'72' => '73 Nights',
					'74' => '74 Nights',
					'75' => '75 Nights',
					'76' => '76 Nights',
					'77' => '77 Nights',
					'78' => '78 Nights',
					'79' => '79 Nights',
					'80' => '80 Nights',
					'81' => '81 Nights',
					'82' => '82 Nights',
					'83' => '83 Nights',
					'84' => '84 Nights',
					'85' => '85 Nights',
					'86' => '86 Nights',
					'87' => '87 Nights',
					'88' => '88 Nights',
					'89' => '89 Nights',
					'90' => '90 Nights',
					'91' => '91 Nights',
					'92' => '92 Nights',
					'93' => '93 Nights',
					'94' => '94 Nights',
					'95' => '95 Nights',
					'96' => '96 Nights',
					'97' => '97 Nights',
					'98' => '98 Nights',
					'99' => '99 Nights',
					'100' => '100 Nights'
			    ),
			    'default'  => '28',
			),
			array(
                'id'       => 'booking_page_url',
                'type'     => 'text',
                'title'    => esc_html__( 'Booking Page URL', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'Please enter page URL in a valid format e.g. http://website.com/page', 'sohohotel' ),
                'default'  => '',
            ),
			array(
                'id'       => 'currency_unit',
                'type'     => 'text',
                'title'    => esc_html__( 'Currency symbol', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'e.g. &#36;, &pound;, &euro;, &yen;, USD', 'sohohotel' ),
                'default'  => '$',
            ),
			array(
                'id'       => 'currency_position',
                'type'     => 'checkbox',
                'title'    => esc_html__( 'Currency symbol position', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'Display currency symbol right of the price', 'sohohotel' ),
                'default'  => '0'// 1 = on | 0 = off
            ),
			array(
                'id'       => 'price_thousand_separator',
                'type'     => 'text',
                'title'    => esc_html__( 'Price Thousand Separator', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => ',',
            ),
			array(
                'id'       => 'price_decimal_separator',
                'type'     => 'text',
                'title'    => esc_html__( 'Price Decimal Separator', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => '.',
            ),
			array(
			    'id'       => 'price_decimal_places',
			    'type'     => 'select',
			    'title'    => __('Price Decimal Places', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => '',
			    'options'  => array(
					'1' => '1',
					'2' => '2',
					'3' => '3',
					'4' => '4',
					'5' => '5',
					'6' => '6',
					'7' => '7',
					'8' => '8',
					'9' => '9',
					'10' => '10'
			    ),
			    'default'  => '2',
			),
			array(
			    'id'       => 'deposit_percentage',
			    'type'     => 'select',
			    'title'    => __('Deposit Percentage (%)', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => '',
			    'options'  => array(
					'1' => '1%',
					'2' => '2%',
					'3' => '3%',
					'4' => '4%',
					'5' => '5%',
					'6' => '6%',
					'7' => '7%',
					'8' => '8%',
					'9' => '9%',
					'10' => '10%',
					'11' => '11%',
					'12' => '12%',
					'13' => '13%',
					'14' => '14%',
					'15' => '15%',
					'16' => '16%',
					'17' => '17%',
					'18' => '18%',
					'19' => '19%',
					'20' => '20%',
					'21' => '21%',
					'22' => '22%',
					'23' => '23%',
					'24' => '24%',
					'25' => '25%',
					'26' => '26%',
					'27' => '27%',
					'28' => '28%',
					'29' => '29%',
					'30' => '30%',
					'31' => '31%',
					'32' => '32%',
					'33' => '33%',
					'34' => '34%',
					'35' => '35%',
					'36' => '36%',
					'37' => '37%',
					'38' => '38%',
					'39' => '39%',
					'40' => '40%',
					'41' => '41%',
					'42' => '42%',
					'43' => '43%',
					'44' => '44%',
					'45' => '45%',
					'46' => '46%',
					'47' => '47%',
					'48' => '48%',
					'49' => '49%',
					'50' => '50%',
					'51' => '51%',
					'52' => '52%',
					'53' => '53%',
					'54' => '54%',
					'55' => '55%',
					'56' => '56%',
					'57' => '57%',
					'58' => '58%',
					'59' => '59%',
					'60' => '60%',
					'61' => '61%',
					'62' => '62%',
					'63' => '63%',
					'64' => '64%',
					'65' => '65%',
					'66' => '66%',
					'67' => '67%',
					'68' => '68%',
					'69' => '69%',
					'70' => '70%',
					'71' => '71%',
					'72' => '72%',
					'73' => '73%',
					'74' => '74%',
					'75' => '75%',
					'76' => '76%',
					'77' => '77%',
					'78' => '78%',
					'79' => '79%',
					'80' => '80%',
					'81' => '81%',
					'82' => '82%',
					'83' => '83%',
					'84' => '84%',
					'85' => '85%',
					'86' => '86%',
					'87' => '87%',
					'88' => '88%',
					'89' => '89%',
					'90' => '90%',
					'91' => '91%',
					'92' => '92%',
					'93' => '93%',
					'94' => '94%',
					'95' => '95%',
					'96' => '96%',
					'97' => '97%',
					'98' => '98%',
					'99' => '99%',
					'100' => '100%'
			    ),
			    'default'  => '25',
			),
			array(
                'id'       => 'booking_success_message',
                'type'     => 'textarea',
                'title'    => esc_html__( 'Booking success message', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => 'Details of your reservation have just been sent to you in a confirmation email, we look forward to seeing you soon. In the meantime if you have any questions feel free to contact us.',
            ),
			array(
                'id'       => 'payment_success_message',
                'type'     => 'textarea',
                'title'    => esc_html__( 'Payment success message', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => 'Your payment has been received, we look forward to seeing you soon!',
            ),
			array(
                'id'       => 'terms_conditions',
                'type'     => 'textarea',
                'title'    => esc_html__( 'Terms and conditions', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => '',
            ),
			array(
                'id'       => 'booking_email_subject_guest',
                'type'     => 'text',
                'title'    => esc_html__( 'Guest confirmation email subject', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => 'Soho Hotel Booking Confirmation',
            ),
			array(
                'id'       => 'booking_email_content_guest',
                'type'     => 'textarea',
                'title'    => esc_html__( 'Guest confirmation email message', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'Sent to the guest when they place a booking', 'sohohotel' ),
                'default'  => 'Thanks for booking with Soho Hotel, we look forward to seeing you soon! If you have any questions please don\'t hesitate to get in touch.',
            ),
			array(
                'id'       => 'booking_email_subject_admin',
                'type'     => 'text',
                'title'    => esc_html__( 'Admin confirmation email subject', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => '',
                'default'  => 'Soho Hotel New Booking Received',
            ),
			array(
                'id'       => 'booking_email_content_admin',
                'type'     => 'textarea',
                'title'    => esc_html__( 'Admin confirmation email message', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'Sent to the admin when a guest places a booking', 'sohohotel' ),
                'default'  => 'A new booking has been placed, please see below for details',
            ),
			array(
                'id'       => 'custom_booking_form',
                'type'     => 'textarea',
                'title'    => esc_html__( 'Custom Booking Form Fields', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'Used for the booking form on booking step 3 where guests enter their details', 'sohohotel' ),
                'default'  => '<div class="input-field-one-half">
[text required id="first_name" label="First Name"]
</div>

<div class="input-field-one-half last-col">
[text required id="last_name" label="Last Name"]
</div>

<div class="input-field-one-half">
[text required id="email_address" class="email_validation" label="Email Address"]
</div>

<div class="input-field-one-half last-col">
[text required id="telephone" class="number_validation" label="Telephone"]
</div>

<div class="input-field-one-half">
[text required id="address_line_1" label="Address Line 1"]
</div>

<div class="input-field-one-half last-col">
[text required id="address_line_2" label="Address Line 2"]
</div>

<div class="input-field-one-half">
[text required id="city" label="City"]
</div>

<div class="input-field-one-half last-col">
[text required id="state" label="State / County"]
</div>

<div class="input-field-one-half">
[text required id="zip" label="Zip / Postcode"]
</div>

<div class="input-field-one-half last-col">
[text required id="country" label="Country"]
</div>

[textarea required id="special_requirements" label="Special Requirements"]',
        ),
		array(
		    'id'       => 'datepicker_days',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Datepicker Days', 'sohohotel' ),
		    'subtitle' => '',
		    'desc'     => esc_html__( 'Do not remove any of the quotemarks, commas or brackets when editing!', 'sohohotel' ),
		    'default'  => "['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']",
		),
		array(
		    'id'       => 'datepicker_months',
		    'type'     => 'textarea',
		    'title'    => esc_html__( 'Datepicker Months', 'sohohotel' ),
		    'subtitle' => '',
		    'desc'     => esc_html__( 'Do not remove any of the quotemarks, commas or brackets when editing!', 'sohohotel' ),
		    'default'  => "['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']",
		)
	    )

	) );
	
	Redux::setSection( $opt_name, array(
	    'title'            => esc_html__( 'iCal', 'sohohotel' ),
	    'id'               => 'iCal',
	    'desc'             => '',
	    'customizer_width' => '400px',
	    'icon'             => 'el el-repeat',
		'fields'           => array(
			array(
                'id'       => 'refresh_ical',
                'type'     => 'info',
                'title'    => esc_html__( 'Manually Refresh iCal Feeds', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'You can manually refresh all iCal feeds by clicking here: ', 'sohohotel' ) . '<a target="_blank" href="' . get_site_url() . '/?sh_ical=sync_all">' . get_site_url() . '/?sh_ical=sync_all</a>',
            ),
			array(
                'id'       => 'auto_refresh_ical',
                'type'     => 'info',
                'title'    => esc_html__( 'Auto Refresh iCal Feeds', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'To auto refresh iCal feeds you should setup a cron job in your web hosting control panel, the command you should run is: wget ' . get_site_url() . '/?sh_ical=sync_all', 'sohohotel' ),
            )
	    )

	) );
	
	Redux::setSection( $opt_name, array(
	    'title'            => esc_html__( 'PayPal', 'sohohotel' ),
	    'id'               => 'paypal',
	    'desc'             => '',
	    'customizer_width' => '400px',
	    'icon'             => 'el el-credit-card',
		'fields'           => array(
			array(
                'id'       => 'disable_paypal',
                'type'     => 'checkbox',
                'title'    => esc_html__( 'Disable PayPal', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'If you check this option PayPal payments will not be available to guests', 'sohohotel' ),
                'default'  => '0'// 1 = on | 0 = off
            ),
			array(
			    'id'       => 'paypal-currency',
			    'type'     => 'select',
			    'title'    => __('PayPal Currency', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => esc_html__( 'The currency PayPal payments will be process with', 'sohohotel' ),
			    'options'  => array(
			        'AUD' => 'AUD (Australian Dollar)',
					'BRL' => 'BRL (Brazilian Real)',
					'CAD' => 'CAD (Canadian Dollar)',
					'CZK' => 'CZK (Czech Koruna)',
					'DKK' => 'DKK (Danish Krone)',
					'EUR' => 'EUR (Euro)',
					'HKD' => 'HKD (Hong Kong Dollar)',
					'HUF' => 'HUF (Hungarian Forint)',
					'ILS' => 'ILS (Israeli New Sheqel)',
					'JPY' => 'JPY (Japanese Yen)',
					'MYR' => 'MYR (Malaysian Ringgit)',
					'MXN' => 'MXN (Mexican Peso)',
					'NOK' => 'NOK (Norwegian Krone)',
					'NZD' => 'NZD (New Zealand Dollar)',
					'PHP' => 'PHP (Philippine Peso)',
					'PLN' => 'PLN (Polish Zloty)',
					'GBP' => 'GBP (Pound Sterling)',
					'RUB' => 'RUB (Russian Ruble)',
					'SGD' => 'SGD (Singapore Dollar)',
					'SEK' => 'SEK (Swedish Krona)',
					'CHF' => 'CHF (Swiss Franc)',
					'TWD' => 'TWD (Taiwan New Dollar)',
					'THB' => 'THB (Thai Baht)',
					'USD' => 'USD (U.S. Dollar)'
			    ),
			    'default'  => 'USD',
			),
			array(
			    'id'       => 'paypal-sandbox',
			    'type'     => 'select',
			    'title'    => __('PayPal Sandbox', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => esc_html__( 'PayPal sandbox allows you to test payments - you should set it to off when you publish your website', 'sohohotel' ),
			    'options'  => array(
			        'true' => 'On',
					'false' => 'Off'
			    ),
			    'false'  => 'Off',
			),
			array(
	            'id'       => 'paypal-address',
	            'type'     => 'text',
	            'title'    => esc_html__( 'PayPal Email Address', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'The email address PayPal payments will be sent to', 'sohohotel' ),
	            'default'  => '',
	        ),
			array(
                'id'       => 'paypal_thankyou',
                'type'     => 'text',
                'title'    => esc_html__( 'PayPal Thank You Page / URL', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'The page guests are redirected to after successfully paying for their booking on PayPal e.g. http://website.com/thankyou, if left blank guests will be redirected to your website homepage', 'sohohotel' ),
                'default'  => '',
            ),
	    )

	) );
	
	Redux::setSection( $opt_name, array(
	    'title'            => esc_html__( 'Stripe', 'sohohotel' ),
	    'id'               => 'stripe',
	    'desc'             => '',
	    'customizer_width' => '400px',
	    'icon'             => 'el el-credit-card',
		'fields'           => array(
			array(
                'id'       => 'disable_stripe',
                'type'     => 'checkbox',
                'title'    => esc_html__( 'Disable Stripe', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'If you check this option Stripe/credit card payments will not be available to guests', 'sohohotel' ),
                'default'  => '0'// 1 = on | 0 = off
            ),
			array(
			    'id'       => 'stripe-currency',
			    'type'     => 'select',
			    'title'    => __('Stripe Currency', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => esc_html__( 'The currency Stripe payments will be process with', 'sohohotel' ),
			    'options'  => array(
			        'AED' => 'United Arab Emirates Dirham',
					'AFN' => 'Afghan Afghani',
					'ALL' => 'Albanian Lek',
					'AMD' => 'Armenian Dram',
					'ANG' => 'Netherlands Antillean Gulden',
					'AOA' => 'Angolan Kwanza',
					'ARS' => 'Argentine Peso',
					'AUD' => 'Australian Dollar',
					'AWG' => 'Aruban Florin',
					'AZN' => 'Azerbaijani Manat',
					'BAM' => 'Bosnia & Herzegovina Convertible Mark',
					'BBD' => 'Barbadian Dollar',
					'BDT' => 'Bangladeshi Taka',
					'BGN' => 'Bulgarian Lev',
					'BIF' => 'Burundian Franc',
					'BMD' => 'Bermudian Dollar',
					'BND' => 'Brunei Dollar',
					'BOB' => 'Bolivian Boliviano',
					'BRL' => 'Brazilian Real',
					'BSD' => 'Bahamian Dollar',
					'BWP' => 'Botswana Pula',
					'BZD' => 'Belize Dollar',
					'CAD' => 'Canadian Dollar',
					'CDF' => 'Congolese Franc',
					'CHF' => 'Swiss Franc',
					'CLP' => 'Chilean Peso',
					'CNY' => 'Chinese Renminbi Yuan',
					'COP' => 'Colombian Peso',
					'CRC' => 'Costa Rican Colón',
					'CVE' => 'Cape Verdean Escudo',
					'CZK' => 'Czech Koruna',
					'DJF' => 'Djiboutian Franc',
					'DKK' => 'Danish Krone',
					'DOP' => 'Dominican Peso',
					'DZD' => 'Algerian Dinar',
					'EGP' => 'Egyptian Pound',
					'ETB' => 'Ethiopian Birr',
					'EUR' => 'Euro',
					'FJD' => 'Fijian Dollar',
					'FKP' => 'Falkland Islands Pound',
					'GBP' => 'British Pound',
					'GEL' => 'Georgian Lari',
					'GIP' => 'Gibraltar Pound',
					'GMD' => 'Gambian Dalasi',
					'GNF' => 'Guinean Franc',
					'GTQ' => 'Guatemalan Quetzal',
					'GYD' => 'Guyanese Dollar',
					'HKD' => 'Hong Kong Dollar',
					'HNL' => 'Honduran Lempira',
					'HRK' => 'Croatian Kuna',
					'HTG' => 'Haitian Gourde',
					'HUF' => 'Hungarian Forint',
					'IDR' => 'Indonesian Rupiah',
					'ILS' => 'Israeli New Sheqel',
					'INR' => 'Indian Rupee',
					'ISK' => 'Icelandic Króna',
					'JMD' => 'Jamaican Dollar',
					'JPY' => 'Japanese Yen',
					'KES' => 'Kenyan Shilling',
					'KGS' => 'Kyrgyzstani Som',
					'KHR' => 'Cambodian Riel',
					'KMF' => 'Comorian Franc',
					'KRW' => 'South Korean Won',
					'KYD' => 'Cayman Islands Dollar',
					'KZT' => 'Kazakhstani Tenge',
					'LAK' => 'Lao Kip',
					'LBP' => 'Lebanese Pound',
					'LKR' => 'Sri Lankan Rupee',
					'LRD' => 'Liberian Dollar',
					'LSL' => 'Lesotho Loti',
					'MAD' => 'Moroccan Dirham',
					'MDL' => 'Moldovan Leu',
					'MGA' => 'Malagasy Ariary',
					'MKD' => 'Macedonian Denar',
					'MMK' => 'Myanmar Kyat',
					'MNT' => 'Mongolian Tögrög',
					'MOP' => 'Macanese Pataca',
					'MRO' => 'Mauritanian Ouguiya',
					'MUR' => 'Mauritian Rupee',
					'MVR' => 'Maldivian Rufiyaa',
					'MWK' => 'Malawian Kwacha',
					'MXN' => 'Mexican Peso',
					'MYR' => 'Malaysian Ringgit',
					'MZN' => 'Mozambican Metical',
					'NAD' => 'Namibian Dollar',
					'NGN' => 'Nigerian Naira',
					'NIO' => 'Nicaraguan Córdoba',
					'NOK' => 'Norwegian Krone',
					'NPR' => 'Nepalese Rupee',
					'NZD' => 'New Zealand Dollar',
					'PAB' => 'Panamanian Balboa',
					'PEN' => 'Peruvian Nuevo Sol',
					'PGK' => 'Papua New Guinean Kina',
					'PHP' => 'Philippine Peso',
					'PKR' => 'Pakistani Rupee',
					'PLN' => 'Polish Złoty',
					'PYG' => 'Paraguayan Guaraní',
					'QAR' => 'Qatari Riyal',
					'RON' => 'Romanian Leu',
					'RSD' => 'Serbian Dinar',
					'RUB' => 'Russian Ruble',
					'RWF' => 'Rwandan Franc',
					'SAR' => 'Saudi Riyal',
					'SBD' => 'Solomon Islands Dollar',
					'SCR' => 'Seychellois Rupee',
					'SEK' => 'Swedish Krona',
					'SGD' => 'Singapore Dollar',
					'SHP' => 'Saint Helenian Pound',
					'TJS' => 'Tajikistani Somoni',
					'SLL' => 'Sierra Leonean Leone',
					'SOS' => 'Somali Shilling',
					'SRD' => 'Surinamese Dollar',
					'STD' => 'São Tomé and Príncipe Dobra',
					'SVC' => 'Salvadoran Colón',
					'SZL' => 'Swazi Lilangeni',
					'THB' => 'Thai Baht',
					'TOP' => 'Tongan Paʻanga',
					'TRY' => 'Turkish Lira',
					'TTD' => 'Trinidad and Tobago Dollar',
					'TWD' => 'New Taiwan Dollar',
					'TZS' => 'Tanzanian Shilling',
					'UAH' => 'Ukrainian Hryvnia',
					'UGX' => 'Ugandan Shilling',
					'USD' => 'United States Dollar',
					'UYU' => 'Uruguayan Peso',
					'UZS' => 'Uzbekistani Som',
					'VND' => 'Vietnamese Đồng',
					'VUV' => 'Vanuatu Vatu',
					'WST' => 'Samoan Tala',
					'XAF' => 'Central African Cfa Franc',
					'XCD' => 'East Caribbean Dollar',
					'XOF' => 'West African Cfa Franc',
					'XPF' => 'Cfp Franc',
					'YER' => 'Yemeni Rial',
					'ZAR' => 'South African Rand',
					'ZMW' => 'Zambian Kwacha'
			    ),
			    'default'  => 'USD',
			),
			array(
			    'id'       => 'stripe-testmode',
			    'type'     => 'select',
			    'title'    => __('Stripe Test Mode', 'sohohotel'), 
			    'subtitle' => '',
			    'desc'     => esc_html__( 'Stripe test mode allows you to test payments - you should set it to off when you publish your publish', 'sohohotel' ),
			    'options'  => array(
			        'on' => 'On',
					'off' => 'Off'
			    ),
			    'false'  => 'Off',
			),
			array(
	            'id'       => 'stripe-test-secret-key',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Test Secret Key', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => '',
	            'default'  => '',
	        ),
			array(
	            'id'       => 'stripe-test-publishable-key',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Test Publishable Key', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => '',
	            'default'  => '',
	        ),
			array(
	            'id'       => 'stripe-live-secret-key',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Live Secret Key', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => '',
	            'default'  => '',
	        ),
			array(
	            'id'       => 'stripe-live-publishable-key',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Live Publishable Key', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => '',
	            'default'  => '',
	        )
	    )

	) );
	
	Redux::setSection( $opt_name, array(
	    'title'            => esc_html__( 'Cash Payments', 'sohohotel' ),
	    'id'               => 'cash-payments',
	    'desc'             => '',
	    'customizer_width' => '400px',
	    'icon'             => 'el el-credit-card',
		'fields'           => array(
			array(
                'id'       => 'disable_cash',
                'type'     => 'checkbox',
                'title'    => esc_html__( 'Disable Cash Payments', 'sohohotel' ),
                'subtitle' => '',
                'desc'     => esc_html__( 'If you check this option cash payments will not be available to guests', 'sohohotel' ),
                'default'  => '0'// 1 = on | 0 = off
            )
	    )

	) );
	
	Redux::setSection( $opt_name, array(
	    'title'            => esc_html__( 'Logo', 'sohohotel' ),
	    'id'               => 'logo',
	    'desc'             => '',
	    'customizer_width' => '400px',
	    'icon'             => 'el el-picture',
		'fields'           => array(
			array(
	            'id'       => 'logo-image',
	            'type'     => 'media',
	            'title'    => esc_html__( 'Logo Image', 'sohohotel' ),
	            'desc'     => esc_html__( 'Add a logo image', 'sohohotel' ),
	            'subtitle' => '',
	        ),
			array(
	            'id'       => 'logo-image-sticky-header',
	            'type'     => 'media',
	            'title'    => esc_html__( 'Logo Image Stick Header', 'sohohotel' ),
	            'desc'     => esc_html__( 'Used for the sticky header when you scroll down the page - this version of your logo should be smaller', 'sohohotel' ),
	            'subtitle' => '',
	        ),
	    )

	) );

	Redux::setSection( $opt_name, array(
		'title'            => esc_html__( 'Colors', 'sohohotel' ),
		'id'               => 'colors',
		'desc'             => '',
		'customizer_width' => '400px',
		'icon'             => 'el el-cog',
		'fields'     => array(
			array(
	            'id'       => 'main-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Main Color', 'sohohotel' ),
	            'subtitle' => '',
	            'default'  => '#b19f6a',
				'validate' => 'color',
	        ),
	        array(
	            'id'       => 'secondary-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Secondary Background Color', 'sohohotel' ),
	            'subtitle' => '',
	            'default'  => '#1c1c1c',
	            'validate' => 'color',
	        ),
			array(
	            'id'       => 'page-background-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Page Background Color', 'sohohotel' ),
	            'subtitle' => esc_html__( 'Note this is only visible if you\'re using the boxed layout', 'sohohotel' ),
	            'default'  => '#666666',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'page-title-background-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Page Title Background Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#f0f0f0',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'page-title-text-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Page Title Text Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#424242',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'header-top-bar-background-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Header Top Bar Background Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#1c1c1c',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'header-top-bar-text-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Header Top Bar Text Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#ffffff',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'header-top-bar-text-separator-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Header Top Bar Separator Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#737373',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'header-top-right-button-background-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Header Top Right Button Background Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#b19f6a',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'header-top-right-button-text-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Header Top Right Button Text Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#ffffff',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'footer-background-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Footer Background Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#1c1c1c',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'footer-text-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Footer Text Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#ffffff',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'footer-text-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Footer Text Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#ffffff',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'footer-bottom-bar-background-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Footer Bottom Bar Background Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#b19f6a',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'footer-bottom-bar-text-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Footer Bottom Bar Text Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#ffffff',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'booking-form-background-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Booking Form Background Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#1c1c1c',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'booking-form-text-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Booking Form Text Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#ffffff',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'booking-form-price-border-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Booking Form Price Border Color', 'sohohotel' ),
	            'subtitle' => esc_html__( 'Only visible on the accommodation single page booking form, the border is displayed around the quoted room price', 'sohohotel' ),
	            'default'  => '#494949',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'booking-form-button-background-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Booking Form Button Background Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#b19f6a',
				'validate' => 'color',
	        ),
			array(
	            'id'       => 'booking-form-button-text-color',
	            'type'     => 'color',
	            'title'    => esc_html__( 'Booking Form Button Text Color', 'sohohotel' ),
	            'subtitle' => esc_html__( '', 'sohohotel' ),
	            'default'  => '#ffffff',
				'validate' => 'color',
	        )
		)
	) );

	Redux::setSection( $opt_name, array(
	    'title'            => esc_html__( 'Fonts', 'sohohotel' ),
	    'id'               => 'fonts',
	    'desc'             => '',
	    'customizer_width' => '400px',
	    'icon'             => 'el el-font',
		'fields'     => array(
			array(
	            'id'       => 'google_font_name_1',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Font Family 1 (Used For Titles)', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( "e.g. 'Playfair Display', serif", 'sohohotel' ),
	            'default'  => "'Playfair Display', serif",
	        ),
			array(
	            'id'       => 'google_font_url_1',
	            'type'     => 'textarea',
	            'title'    => esc_html__( 'Font URL 1', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( "Only required if you're using Google Fonts or similar, e.g. Playfair+Display:400,400i,700,700i,900,900i", 'sohohotel' ),
	            'default'  => "Playfair+Display:400,400i,700,700i,900,900i",
	        ),	
			array(
	            'id'       => 'google_font_name_2',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Font Family 2 (Used For Body)', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( "e.g. 'Source Sans Pro', sans-serif", 'sohohotel' ),
	            'default'  => "'Source Sans Pro', sans-serif",
	        ),
			array(
	            'id'       => 'google_font_url_2',
	            'type'     => 'textarea',
	            'title'    => esc_html__( 'Font URL 2', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( "Only required if you're using Google Fonts or similar, e.g. Source Sans Pro:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900,900italic", 'sohohotel' ),
	            'default'  => "Source Sans Pro:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900,900italic",
	        ),
		)
	) );

	Redux::setSection( $opt_name, array(
	    'title'            => esc_html__( 'Page Header', 'sohohotel' ),
	    'id'               => 'page-header',
	    'desc'             => '',
	    'customizer_width' => '400px',
	    'icon'             => 'el el-file',
		'fields'     => array(
	        array(
	            'id'       => 'page-header-image',
	            'type'     => 'media',
	            'title'    => esc_html__( 'Default Page Header Image', 'sohohotel' ),
	            'desc'     => esc_html__( 'Displayed on all pages a header image is not set in the page options', 'sohohotel' ),
	            'subtitle' => '',
	        ),
			array(
	            'id'       => 'page-not-found',
	            'type'     => 'media',
	            'title'    => esc_html__( '404 Page Not Found Background Image', 'sohohotel' ),
	            'desc'     => esc_html__( 'Displayed on the 404 not found page', 'sohohotel' ),
	            'subtitle' => '',
	        ),
			array(
	            'id'       => 'booking-page-image',
	            'type'     => 'media',
	            'title'    => esc_html__( 'Booking Page Background Image', 'sohohotel' ),
	            'desc'     => esc_html__( 'Displayed on the booking page', 'sohohotel' ),
	            'subtitle' => '',
	        )
		)
	) );
	
	Redux::setSection( $opt_name, array(
	    'title'            => esc_html__( 'Custom JS', 'sohohotel' ),
	    'id'               => 'custom-js',
	    'desc'             => '',
	    'customizer_width' => '400px',
	    'icon'             => 'el el-edit',

		'fields'     => array(
	        array(
	            'id'       => 'custom_js',
	            'type'     => 'textarea',
	            'title'    => esc_html__( 'Custom JS', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Add your own custom JS to the theme', 'sohohotel' ),
	            'default'  => '',
			),
		)
	) );

	Redux::setSection( $opt_name, array(
		'title'            => esc_html__( 'Social', 'sohohotel' ),
		'id'               => 'social',
		'desc'             => '',
		'customizer_width' => '400px',
		'icon'             => 'el el-facebook',
		'fields'           => array(
			array(
	            'id'       => 'social-link-target',
	            'type'     => 'checkbox',
	            'title'    => esc_html__( 'Open social links in new window/tab', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => '',
	            'default'  => '1'// 1 = on | 0 = off
	        ),
			array(
	            'id'       => 'facebook-icon',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Facebook URL', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Enter URL e.g. http://website.com/username', 'sohohotel' ),
	            'default'  => '',
	        ),
			array(
	            'id'       => 'flickr-icon',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Flickr URL', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Enter URL e.g. http://website.com/username', 'sohohotel' ),
	            'default'  => '',
	        ),
			array(
	            'id'       => 'googleplus-icon',
	            'type'     => 'text',
	            'title'    => esc_html__( 'GooglePlus URL', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Enter URL e.g. http://website.com/username', 'sohohotel' ),
	            'default'  => '',
	        ),
			array(
	            'id'       => 'instagram-icon',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Instagram URL', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Enter URL e.g. http://website.com/username', 'sohohotel' ),
	            'default'  => '',
	        ),
			array(
	            'id'       => 'pinterest-icon',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Pinterest URL', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Enter URL e.g. http://website.com/username', 'sohohotel' ),
	            'default'  => '',
	        ),
			array(
	            'id'       => 'skype-icon',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Skype URL', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Enter URL e.g. http://website.com/username', 'sohohotel' ),
	            'default'  => '',
	        ),
			array(
	            'id'       => 'soundcloud-icon',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Soundcloud URL', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Enter URL e.g. http://website.com/username', 'sohohotel' ),
	            'default'  => '',
	        ),
			array(
	            'id'       => 'tumblr-icon',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Tumblr URL', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Enter URL e.g. http://website.com/username', 'sohohotel' ),
	            'default'  => '',
	        ),
			array(
	            'id'       => 'twitter-icon',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Twitter URL', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Enter URL e.g. http://website.com/username', 'sohohotel' ),
	            'default'  => '',
	        ),
			array(
	            'id'       => 'vimeo-icon',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Vimeo URL', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Enter URL e.g. http://website.com/username', 'sohohotel' ),
	            'default'  => '',
	        ),
			array(
	            'id'       => 'vine-icon',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Vine URL', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Enter URL e.g. http://website.com/username', 'sohohotel' ),
	            'default'  => '',
	        ),
			array(
	            'id'       => 'yelp-icon',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Yelp URL', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Enter URL e.g. http://website.com/username', 'sohohotel' ),
	            'default'  => '',
	        ),
			array(
	            'id'       => 'youtube-icon',
	            'type'     => 'text',
	            'title'    => esc_html__( 'Youtube URL', 'sohohotel' ),
	            'subtitle' => '',
	            'desc'     => esc_html__( 'Enter URL e.g. http://website.com/username', 'sohohotel' ),
	            'default'  => '',
	        ),
	    )
	) );